- hosts: docker-server
  vars:
    max_retries: 3
    retry_counter: 0 
  tasks:
  - name: repeat block task with loop
    ansible.builtin.include_tasks: tasks.yml
    with_sequence: start=0 end={{ max_retries }} 
